# Generated by Django 5.2.1 on 2025-05-31 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya Nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya_nomi', models.CharField(max_length=200, verbose_name='Kompaniya Nomi')),
                ('aloqa_shaxs', models.CharField(max_length=100, verbose_name="Mas'ul Shaxs")),
                ('telefon', models.CharField(max_length=20, unique=True, verbose_name='Telefon Raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Manzili')),
                ('manzil', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Mahsulot Nomi')),
                ('artikul', models.CharField(max_length=50, unique=True, verbose_name='Artikul (SKU)')),
                ('rangi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rangi')),
                ('olchami', models.CharField(blank=True, max_length=50, null=True, verbose_name="O'lchami")),
                ('sotib_olish_narxi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sotib Olish Narxi ($)')),
                ('sotish_narxi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sotish Narxi ($)')),
                ('qoldiq', models.PositiveIntegerField(default=0, verbose_name='Ombordagi Qoldiq (dona)')),
                ('tavsif', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha Tavsif")),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan Sana")),
                ('yangilangan_sana', models.DateTimeField(auto_now=True, verbose_name='Yangilangan Sana')),
                ('kategoriya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_app.kategoriya', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-qoshilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='SotuvBuyurtmasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurtma_sanasi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Buyurtma Sanasi')),
                ('umumiy_summa', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Umumiy Summa ($)')),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ('Tasdiqlangan', 'Tasdiqlangan'), ("Jo'natilgan", "Jo'natilgan"), ('Yetkazilgan', 'Yetkazilgan'), ('Bekor qilingan', 'Bekor qilingan')], default='Yangi', max_length=20, verbose_name='Statusi')),
                ('izoh', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.mijoz', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Sotuv Buyurtmasi',
                'verbose_name_plural': 'Sotuv Buyurtmalari',
                'ordering': ['-buyurtma_sanasi'],
            },
        ),
        migrations.CreateModel(
            name='SotuvBuyurtmasiElementi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.PositiveIntegerField(default=1, verbose_name='Miqdori (dona)')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi (birlik uchun $)')),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementlar', to='erp_app.sotuvbuyurtmasi', verbose_name='Sotuv Buyurtmasi')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.mahsulot', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Sotuv Buyurtmasi Elementi',
                'verbose_name_plural': 'Sotuv Buyurtmasi Elementlari',
            },
        ),
    ]
