# Generated by Django 5.2.1 on 2025-05-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuvbuyurtmasielementi',
            name='narx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Narxi (birlik uchun $)'),
        ),
    ]
